default_stages: [commit]

repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
